pipeline {
    agent any

    stages {
        stage("build app") {
            steps {
		        echo 'build with npm'
                // Needs to have the same name as the NodeJS installation in Jenkins
                nodejs('nodejs') {
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }

        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deploy.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }   
}
